# Generated by Django 4.2.25 on 2025-10-19 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=8)),
                ('tx_ref', models.CharField(max_length=128, unique=True)),
                ('chapa_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('chapa_checkout_url', models.URLField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='listings.booking')),
            ],
        ),
    ]
